resources:
  - url: /community_plugin/vertical-stack-in-card/vertical-stack-in-card.js
    type: js
  - url: /community_plugin/button-entity-row/button-entity-row.js
    type: js
  - url: /community_plugin/mini-graph-card/mini-graph-card.js
    type: module
  - url: /community_plugin/lovelace-markdown-mod/markdown-mod.js
    type: module
  - url: /community_plugin/lovelace-grocy-chores-card/grocy-chores-card.js
    type: js
  - url: /community_plugin/lovelace-home-feed-card/home-feed-card.js
    type: js
  - url: /community_plugin/upcoming-media-card/upcoming-media-card.js
    type: js
  - url: /local/nest-layout-card.js
    type: js
  - type: js
    url: /local/my-custom-card.js
  - type: module
    url: /local/compact-custom-header.js
  - type: js
    url: /local/card-tools.js
  - type: css
    url: /local/my-webfont.css
  - type: module
    url: /local/button-card.js
  - type: module
    url: /local/card-mod.js
  - type: module
    url: /local/atomic_calendar.js
  - type: module
    url: /local/decluttering-card.js
  - type: module
    url: >-
      https://cdn.jsdelivr.net/gh/bramkragten/weather-card/dist/weather-card.min.js

cch:
  disable: false
  header: true
  menu: true
  sidebar_close: false
  notifications: false
  voice: false
  options: clock
  clock_format: 24
  clock_date: true
  date_locale: no-NO
  swipe: true
  exceptions:
    - conditions:
        user: stua
      config:
        swipe: true
        kiosk_mode: true
decluttering_templates:
  camera_button:
    card:
      type: custom:button-card
      entity: '[[entity]]'
      icon: '[[icon]]'
      show_state: false
      show_icon: true
      show_name: false
      tap_action:
        action: toggle
      style: |
        ha-card {
          # font-family: 'Open Sans', sans-serif;
          padding-top: 10px !important;
          background-color: rgba(0, 0, 0, 0);
          -webkit-box-shadow: none;
          -moz-box-shadow: none;
          box-shadow: none;
        }    
  nest_button:
    default:
      - show_state: true
      - show_name: false
    card:
      type: custom:button-card
      entity: '[[entity]]'
      show_last_changed: true
      show_state: '[[show_state]]'
      show_icon: true
      show_name: '[[show_name]]'
      name: '[[name]]'
      state: '[[state]]'
      tap_action:
        action: more-info
      style: |
        ha-card {
          font-family: 'Open Sans', sans-serif;
          padding-top: 15px !important;
          background-color: rgba(0, 0, 0, 0);
          -webkit-box-shadow: none;
          -moz-box-shadow: none;
          box-shadow: none;
        }
        ha-icon {
          width: 60% !important;
        }
        img {
          width: 100%;
        }
        #img-cell {
          background-color: #F5F5F5;
          border-radius: 50px;
          height: 50px !important;
          width: 50px !important;
        }
        #state {
          padding-top: 5px;
        }
        #label {
          font-size: 70%;
        }
  nest_picture_button:
    card:
      type: custom:button-card
      entity: '[[entity]]'
      show_state: true
      show_icon: true
      show_name: false
      show_entity_picture: true
      entity_picture: '[[entity_picture]]'
      tap_action:
        action: more-info
      style: |
        ha-card {
          font-family: 'Open Sans', sans-serif;
          padding-top: 15px !important;
          background-color: rgba(0, 0, 0, 0);
          -webkit-box-shadow: none;
          -moz-box-shadow: none;
          box-shadow: none;
        }
        img {
          width: 100% !important;
        }
        #img-cell {
          background-color: #F5F5F5;
          border-radius: 50px;
          height: 50px !important;
          width: 50px !important;
        }
        #state {
          padding-top: 5px;
        }
  barnevakt:
    default:
      - show_state: true
      - show_name: false
    card:
      type: custom:button-card
      entity: '[[entity]]'
      show_last_changed: true
      show_state: '[[show_state]]'
      show_icon: true
      show_name: '[[show_name]]'
      name: '[[name]]'
      state: '[[state]]'
      tap_action:
        action: call-service
        service: homeassistant.toggle
        service_data:
          entity_id: group.barnevaktmodus
      style: |
        ha-card {
          font-family: 'Open Sans', sans-serif;
          padding-top: 15px !important;
          background-color: rgba(0, 0, 0, 0);
          -webkit-box-shadow: none;
          -moz-box-shadow: none;
          box-shadow: none;
        }
        ha-icon {
          width: 60% !important;
        }
        img {
          width: 100%;
        }
        #img-cell {
          background-color: #F5F5F5;
          border-radius: 50px;
          height: 50px !important;
          width: 50px !important;
        }
        #state {
          padding-top: 5px;
        }
        #label {
          font-size: 70%;
        }
  party:
    default:
      - show_state: true
      - show_name: false
    card:
      type: custom:button-card
      entity: '[[entity]]'
      show_last_changed: true
      show_state: '[[show_state]]'
      show_icon: true
      show_name: '[[show_name]]'
      name: '[[name]]'
      state: '[[state]]'
      tap_action:
        action: call-service
        service: homeassistant.toggle
        service_data:
          entity_id: group.partymode
      style: |
        ha-card {
          font-family: 'Open Sans', sans-serif;
          padding-top: 15px !important;
          background-color: rgba(0, 0, 0, 0);
          -webkit-box-shadow: none;
          -moz-box-shadow: none;
          box-shadow: none;
        }
        ha-icon {
          width: 60% !important;
        }
        img {
          width: 100%;
        }
        #img-cell {
          background-color: #F5F5F5;
          border-radius: 50px;
          height: 50px !important;
          width: 50px !important;
        }
        #state {
          padding-top: 5px;
        }
        #label {
          font-size: 70%;
        }
  ferie:
    default:
      - show_state: true
      - show_name: false
    card:
      type: custom:button-card
      entity: '[[entity]]'
      show_last_changed: true
      show_state: '[[show_state]]'
      show_icon: true
      show_name: '[[show_name]]'
      name: '[[name]]'
      state: '[[state]]'
      tap_action:
        action: call-service
        service: homeassistant.toggle
        service_data:
          entity_id: group.feriemodus
      style: |
        ha-card {
          font-family: 'Open Sans', sans-serif;
          padding-top: 15px !important;
          background-color: rgba(0, 0, 0, 0);
          -webkit-box-shadow: none;
          -moz-box-shadow: none;
          box-shadow: none;
        }
        ha-icon {
          width: 60% !important;
        }
        img {
          width: 100%;
        }
        #img-cell {
          background-color: #F5F5F5;
          border-radius: 50px;
          height: 50px !important;
          width: 50px !important;
        }
        #state {
          padding-top: 5px;
        }
        #label {
          font-size: 70%;
        }
  light_button:
    default:
      - show_state: true
      - show_name: false
    card:
      type: custom:button-card
      entity: '[[entity]]'
      show_last_changed: true
      show_state: '[[show_state]]'
      show_icon: true
      show_name: '[[show_name]]'
      name: '[[name]]'
      state: '[[state]]'
      tap_action:
        action: toggle
      style: |
        ha-card {
          font-family: 'Open Sans', sans-serif;
          padding-top: 15px !important;
          background-color: rgba(0, 0, 0, 0);
          -webkit-box-shadow: none;
          -moz-box-shadow: none;
          box-shadow: none;
        }
        ha-icon {
          width: 60% !important;
        }
        img {
          width: 100%;
        }
        #img-cell {
          background-color: #F5F5F5;
          border-radius: 50px;
          height: 50px !important;
          width: 50px !important;
        }
        #state {
          padding-top: 5px;
        }
        #label {
          font-size: 70%;
        }
  vasking:
    default:
      - show_state: true
      - show_name: false
    card:
      type: custom:button-card
      entity: '[[entity]]'
      show_last_changed: true
      show_state: '[[show_state]]'
      show_icon: true
      show_name: '[[show_name]]'
      name: '[[name]]'
      state: '[[state]]'
      tap_action:
        action: call-service
        service: script.turn_on
        service_data:
          entity_id: script.15521539446999
      style: |
        ha-card {
          font-family: 'Open Sans', sans-serif;
          padding-top: 15px !important;
          background-color: rgba(0, 0, 0, 0);
          -webkit-box-shadow: none;
          -moz-box-shadow: none;
          box-shadow: none;
        }
        ha-icon {
          width: 60% !important;
        }
        img {
          width: 100%;
        }
        #img-cell {
          background-color: #F5F5F5;
          border-radius: 50px;
          height: 50px !important;
          width: 50px !important;
        }
        #state {
          padding-top: 5px;
        }
        #label {
          font-size: 70%;
        }
  daglig:
    default:
      - show_state: true
      - show_name: false
    card:
      type: custom:button-card
      entity: '[[entity]]'
      show_last_changed: true
      show_state: '[[show_state]]'
      show_icon: true
      show_name: '[[show_name]]'
      name: '[[name]]'
      state: '[[state]]'
      tap_action:
        action: call-service
        service: script.turn_on
        service_data:
          entity_id: script.15521539430774
      style: |
        ha-card {
          font-family: 'Open Sans', sans-serif;
          padding-top: 15px !important;
          background-color: rgba(0, 0, 0, 0);
          -webkit-box-shadow: none;
          -moz-box-shadow: none;
          box-shadow: none;
        }
        ha-icon {
          width: 60% !important;
        }
        img {
          width: 100%;
        }
        #img-cell {
          background-color: #F5F5F5;
          border-radius: 50px;
          height: 50px !important;
          width: 50px !important;
        }
        #state {
          padding-top: 5px;
        }
        #label {
          font-size: 70%;
        }
  film:
    default:
      - show_state: true
      - show_name: false
    card:
      type: custom:button-card
      entity: '[[entity]]'
      show_last_changed: true
      show_state: '[[show_state]]'
      show_icon: true
      show_name: '[[show_name]]'
      name: '[[name]]'
      state: '[[state]]'
      tap_action:
        action: call-service
        service: script.turn_on
        service_data:
          entity_id: script.15521539430774
      style: |
        ha-card {
          font-family: 'Open Sans', sans-serif;
          padding-top: 15px !important;
          background-color: rgba(0, 0, 0, 0);
          -webkit-box-shadow: none;
          -moz-box-shadow: none;
          box-shadow: none;
        }
        ha-icon {
          width: 60% !important;
        }
        img {
          width: 100%;
        }
        #img-cell {
          background-color: #F5F5F5;
          border-radius: 50px;
          height: 50px !important;
          width: 50px !important;
        }
        #state {
          padding-top: 5px;
        }
        #label {
          font-size: 70%;
        }
title: Nordveien 4
views:
  - !include lovelace/home.yaml
  - !include lovelace/auto.yaml
  - !include lovelace/kjeller.yaml
  - !include lovelace/tab.yaml
  - !include lovelace/dashboard.yaml



 